apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-failed-pods
  namespace: jira
spec:
  schedule: "*/30 * * * *" # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: delete-failed-pods
            image: your-docker-registry/delete-failed-pods:latest
            env:
            - name: NAMESPACE
              value: "jira" # Update this to the namespace you want to monitor
          restartPolicy: OnFailure
